server.port = 30001

server.servlet.context-path = /api

# Maximum upload file size for Spring MVC
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

# Maximum JSON string length for Jackson
jackson.stream.max-string-length=230000000

sofia.uri = http://4.232.76.64/middleware-dev/api
#sofia.uri = http://localhost:15602/api

springdoc.packages-to-scan= it.eng.onenet.dsp.api.controller.consume_data,\
                            it.eng.onenet.dsp.api.controller.offered_services,\
                            it.eng.onenet.dsp.api.controller.provide_data, \
                            it.eng.onenet.dsp.api.controller.user,

logging.level.it.eng.onenet.dsp.api.service.local_functionality=DEBUG
logging.level.it.eng.onenet.dsp.api.rest_template=DEBUG

logging.level.it.eng.onenet.dsp.api.controller.health=DEBUG
logging.level.it.eng.onenet.dsp.api.service.health=DEBUG

logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

push.encryption.key=qX7!2vF9#eT1yH8k

# dsp-connector
jsonObjects.folder.path=classpath:
# public connector endpoint url
connector.endpoint.url=http://172.17.0.1:8080
# internal connector endpoint url
connector.base.url=http://localhost:8080
connector.api=/api/v1/
connector.endpoint.api.url=${connector.base.url}${connector.api}
connector.basic.auth=YWRtaW5AbWFpbC5jb206cGFzc3dvcmQ=

# Max polling attempts to check download completion (default: ~15 minutes)
transfer.poll.max-retries=180
# Delay in milliseconds between each retry (default: 5 seconds)
transfer.poll.delay-millis=5000

#connector-init
connector.init.max-attempts=30
connector.init.wait-ms=5000
connector.init.timeout-ms=500
#dsp-connector

# notification-module
connector.enable.notifications=false
notification.module.endpoint=http://localhost:3055/api/v1
# notification-module