server.port = 30001

server.servlet.context-path = /api

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

sofia.uri = http://4.232.76.64/middleware-dev/api
#sofia.uri = http://localhost:15602/api

springdoc.packages-to-scan= it.eng.onenet.dsp.api.controller.consume_data,\
                            it.eng.onenet.dsp.api.controller.offered_services,\
                            it.eng.onenet.dsp.api.controller.provide_data, \
                            it.eng.onenet.dsp.api.controller.user,

logging.level.it.eng.onenet.dsp.api.service.local_functionality=DEBUG
logging.level.it.eng.onenet.dsp.api.rest_template=DEBUG

logging.level.it.eng.onenet.dsp.api.controller.health=DEBUG
logging.level.it.eng.onenet.dsp.api.service.health=DEBUG

logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

# dsp-connector
jsonObjects.folder.path=classpath:
# public connector endpoint url
connector.endpoint.url=http://172.17.0.1:8080
# internal connector endpoint url
connector.base.url=http://localhost:8080
connector.api=/api/v1/
connector.endpoint.api.url=${connector.base.url}${connector.api}
connector.basic.auth=YWRtaW5AbWFpbC5jb206cGFzc3dvcmQ=
#dsp-connector